# Generated by Django 4.0 on 2022-02-08 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='content',
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='taskDesc',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='taskTitle',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 8, 10, 17, 40, 51952, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
